### ISSUE TITLE
Some lag and bugs encountered on MacOS

### ISSUE THREAD

**Issue by Celso-Scott** [czcorpus/InterText_editor#5]
Hi, I've been working on an alignment project with some editors using different operating systems. InterText's workflow has been quite smooth on Windows and Linux, but for MacOS we have been noticing a few issues:

1) Every time you bump a unit into the segment above it appears to vanish until you double click into that cell or wait for about 5-10 seconds (Another TM editor reported this same problem). 
2) generally it is a lot more lagy than on PC, I found that it takes an extra half second or so between each command, although this may have been an issue with the computer I was testing, which is not my usual one.

For MacOS, I really only have two test cases on this, so perhaps it would work better on different OS versions. But, I'm finding that while it is still functional, I think the lag may be an issue for creating an efficient workflow. Anyways, I don't want to complain, as InterText is working fabulously on PCs, but I just wanted to give this point as feedback.

**Comment by wanthalf** [comment]
Hi, thanks for reporting. I can confirm the first issue, but I cannot confirm the second problem with laggy behaviour. The Mac version is the only one updated lately to 1.6.1 (mainly because a Mac specific problem was fixed in the last update) and it is the only one compiled with a newer Qt-toolkit, so I suppose there could be some changes in the Qt causing the problem. I will try to find out what happened.

**Comment by wanthalf** [comment]
So, I heave really no idea why it stopped working just in this single case, but it seems to happen also in Windows when recompiled. Somehow it did not get fixed by downgrading Qt either. Strange.

So, I made a simple workaround by enforcing the automatic resizing of all the visible table rows as done when scrolling the table. It has a slight lag (by purpose) and have also lowered the lag a bit. I released the update as version 1.6.2. Please, try it and let me know, how does it feel in your environment.

As for the laggy behaviour: the automatic resizing has been a pain for all the time and the current solution is not the best one, but it scales best also for long texts. Anyway, the lag should still be in the comfortable zone of fractions of second, definitely not several seconds! It can be more evident if you have very long text elements (sentences) and it can still become unusable if you put hundreds of sentences into a single segment (table row)larger than your application window. But in usual situations (segments with 1-10 sentences), it should behave very quickly in all cases. I develop and test the application mainly on an iMac from 2011 using latest compatible MacOS (10.13) and I have never noticed uncomfortably laggy behaviour, even with very long texts (30-60000 segments).

**Comment by Celso-Scott** [comment]
Wow, that's great. Thanks so much for your fix on this. Yes, I suspect the general lag issue probably has more to do with the mac I was testing on. I have two mac users working on this project, so I will tell them to try this new version 1.6.2 and let you know what they say.

**Comment by Celso-Scott** [comment]
Sorry about this, I'm not really a developer so I'm not sure how to install InterText from the source code on a mac, and I suspect the two mac users will not know either. If you haven't already would you mind applying the new version to the MacOS Installer on your website? 

https://wanthalf.saga.cz/doc_intertext

**Comment by wanthalf** [comment]
If you already have InterText installed, it will tell you there is a new version available a few seconds after you start it. If you agree, it will start the install/update utility where you can update to the new version (and then you just close the installer by clicking on the "Done" button). When the update is installed, InterText will ask you, whether you want to restart the application - then you get the new version.

When installing from the scratch, the installer will automatically install the newest version available.

(Note: I only compiled the version 1.6.2 for MacOS, you won't get it on Windows nor Linux, of course.)

**Comment by Celso-Scott** [comment]
Wonderful, Thank you for the clarification, and apologies for my lack of technical knowledge. I have informed my mac users and I will let you know how they are carrying on.

**Comment by Celso-Scott** [comment]
I checked with my mac users and also got a chance to try 1.6.2 myself. Works beautifully, thank you very much!
